-- Autocmds are automatically loaded on the VeryLazy event
-- Default autocmds that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/autocmds.lua
-- Add any additional autocmds here
--vim.cmd("TwilightEnable")
vim.cmd("set guifont=JetBrainsMono_NF:h11")
--vim.cmd("GonvimMiniMap")
--vim.cmd("GonvimLigatures")
--vim.cmd("GonvimSmoothScroll")
--vim.cmd("GonvimSmoothCursor")
--vim.cmd("GonvimIndentguide")
--vim.cmd("GonvimMousescrollUnit smart")
--vim.cmd("TransparentEnable")
--vim.cmd("lazy redraw")