return {
  { "catppuccin", enabled = false },
  { "tokyonight.nvim", enabled = false },
  { "ts-comments.nvim", enabled = false },
  { "friendly-snippets", enabled = false },
  { "dashboard-nvim", enabled = false },
  { "gitsigns.nvim", enabled = false },
  { "luvit-meta", enabled = false },
  { "nvim-snippets", enabled = false },
  { "nvim-ts-autotag", enabled = false },
  --{ "echasnovski/mini.animate", enabled = false },
  --{ "folke/noice.nvim", enabled = true },
  --{ "neo-tree.nvim", enabled = true },
  --  { "twilight.nvim", enabled = false },
  { "nvim-neo-tree/neo-tree.nvim", enabled = false },
  { "folke/flash.nvim", enabled = false },
  { "nvim-treesitter-textobjects", enabled = false },
}
